[Greeter]
background=/usr/share/backgrounds/catos.png
draw-user-backgrounds=false
draw-grid=true
theme-name=Graphite-blue-Dark-nord
icon-theme-name=Tela-circle-blue-dark
cursor-theme-name=Bibata-Modern-Classic
cursor-theme-size=16
show-a11y=false
show-power=false
background-color=#000000
