graphics: yes
wallpaper: boot():/EFI/limine/themes/catos/wallpaper.jpg
wallpaper_style: stretched
interface_branding: CatOS
interface_branding_colour: 9fc8bd
interface_help_colour: 86a99f
interface_help_colour_bright: c7e5dc
term_font: boot():/EFI/limine/themes/catos/font.bin
term_font_size: 8x16
term_font_scale: 1x1
term_font_spacing: 1
term_palette: 09110f;9b5550;719986;a98d67;567889;80657f;75a09d;b9b9af
term_palette_bright: 3a4945;c67a72;9bc6ad;d3b582;80a8bb;aa8cab;a4ceca;edf1ed
term_background: b009110f
term_foreground: dce7e1
term_background_bright: 20312d
term_foreground_bright: f4faf7
term_margin: 14
term_margin_gradient: 24
